{% set name = "databroker-pack" %}
{% set version = "0.2.0" %}
{% set sha256 = "38cbd2112ad64c8b2034d62d9a754cda64800c57e7d5fa472f81c9609a4fdd80" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - databroker-pack = databroker_pack.commandline.pack:main
    - databroker-unpack = databroker_pack.commandline.unpack:main
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - databroker >=1.0.1
    - event-model
    - intake >=0.5.5
    - suitcase-jsonl
    - suitcase-msgpack
    - suitcase-utils
    - tqdm

test:
  imports:
    - databroker_pack
    - databroker_pack.commandline
    - databroker_pack.tests
  commands:
    - databroker-pack --help
    - databroker-unpack --help

about:
  home: https://github.com/bluesky/databroker-pack
  license: BSD (3-clause)
  license_family: BSD
  license_file: LICENSE
  summary: Tools for a portable databroker
